import HautevilleHouse.BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean.BasicHypergeometricRootSystem
import HautevilleHouse.BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean.BasicHypergeometricFunction
import HautevilleHouse.BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean.AskeyWilsonAlgebra
import HautevilleHouse.BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean.KasigawaSaitoTheory
import HautevilleHouse.BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean.HypergeometricClosure

namespace HautevilleHouse
namespace BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean

-- This file is the root of the BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean Lean proof package.
end BasicHypergeometricFunctionsAssociatedRootCanonicalLaneLean
end HautevilleHouse